### ISSUE TITLE
propose: Add First() on slice, empty to return nil

### ISSUE THREAD

**Issue by kangarooxin** [samber/lo#437] opened 2024-03-14 07:40 UTC

**Comment by freeeverett** [comment] 2024-04-20 04:08
When the null value is not nil, I think the function cannot be implemented. Is there any way to implement the function?

**Comment by Alireza-Kiani** [comment] 2024-05-12 00:14
Hey there, just created a pull request similar to what you need https://github.com/samber/lo/pull/451.
Returning zero value instead of `nil` is just more compatible with the conventions

**Comment by shivamrazorpay** [comment] 2024-07-20 05:49
this is fixed.

**Comment by shivamrazorpay** [comment] 2024-07-20 05:49
Issued fixed in : https://github.com/samber/lo/pull/451

**Comment by shivamrazorpay** [comment] 2024-07-20 05:50
@kangarooxin as the issue is fixed, i think you can close it.

**Closed** 2024-07-26 05:35 UTC
